name: glomar_gridding Lint
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint (Python${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 1 # Fetch only current version
          persist-credentials: false

      - name: Set environment variables
        run: |
          echo "UV_ENV_FILE=pyproject.toml" >> $GITHUB_ENV
          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "UV_CACHE_DIR=/tmp/.uv-cache" >> $GITHUB_ENV

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-local-path: ${{ env.UV_CACHE_DIR }}

      - name: Restore uv cache
        uses: actions/cache@v5
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-${{runner.arch}}-py${{matrix.python-version}}-${{ hashFiles(env.UV_ENV_FILE) }}
          restore-keys: |
            uv-${{ runner.os }}-${{runner.arch}}-py${{matrix.python-version}}-${{ hashFiles(env.UV_ENV_FILE) }}
            uv-${{ runner.os }}-${{runner.arch}}-py${{matrix.python-version}}

      - name: Install glomar_gridding
        run: |
          uv sync --group lint

      - name: Version info
        run: |
          uv pip list

      - name: Run linters
        timeout-minutes: 10
        run: |
          uv run ruff check glomar_gridding test
          uv run numpydoc lint glomar_gridding/**.py
          uv run codespell glomar_gridding test docs

      - name: Minimise uv cache
        run: uv cache prune --ci
